Repository NESGroundZero/groundzero-website, pull requests merged in 2022-12, with the labels that each got.

#14 Feature Navigation Bar
  groundzero/index.html
  groundzero/package-lock.json
  groundzero/package.json
  groundzero/src/App.jsx
  groundzero/src/components/About.jsx
  groundzero/src/components/ContactUs.jsx
  groundzero/src/components/NavigationBar.jsx
  groundzero/src/components/ProblemStatements.jsx
  groundzero/src/components/SignUp.jsx
  groundzero/src/components/Timeline.jsx
  groundzero/src/index.css
Labels: enhancement, progress

#16 Contact Us and Partners Skeleton Page
  groundzero/package-lock.json
  groundzero/package.json
  groundzero/src/App.jsx
  groundzero/src/assets/index.jsx
  groundzero/src/components/ContactUs.jsx
  groundzero/src/components/ContactUsCard.jsx
  groundzero/src/components/Partners.jsx
  groundzero/src/components/index.js
  groundzero/src/constants/index.js
Labels: enhancement

#15 Feature - FAQ Page
  groundzero/index.html
  groundzero/src/App.jsx
  groundzero/src/components/Faq.jsx
  groundzero/src/components/index.js
  groundzero/src/constants/index.js
  groundzero/src/index.css
Labels: enhancement, progress

#18 Feature - Workshop Page
  groundzero/src/components/Workshops.jsx
  groundzero/src/constants/index.js
  groundzero/tailwind.config.cjs
Labels: enhancement

#19 Fully functional ContactUs and Partners page
  groundzero/src/assets/accelerating.png
  groundzero/src/assets/aws.png
  groundzero/src/assets/changeMakers.png
  groundzero/src/assets/eatLaunchpad.png
  groundzero/src/assets/index.jsx
  groundzero/src/assets/nes.png
  groundzero/src/assets/nusEnterprise.png
  groundzero/src/assets/nyc.png
  groundzero/src/assets/sginnovate.png
  groundzero/src/assets/startupBuddy.png
  groundzero/src/components/ContactUs.jsx
  groundzero/src/components/ContactUsCard.jsx
  groundzero/src/components/DisplayIcon.jsx
  groundzero/src/components/Partners.jsx
  groundzero/src/components/index.js
  groundzero/src/constants/index.js
  groundzero/src/style.js
Labels: enhancement

#21 Feature: Mentors
  groundzero/package-lock.json
  groundzero/package.json
  groundzero/src/App.jsx
  groundzero/src/components/MentorCard.jsx
  groundzero/src/components/Mentors.jsx
  groundzero/src/components/index.js
  groundzero/src/constants/index.js
Labels: enhancement

#25 Fix Navbar Sticky Position and Broken Links
  groundzero/package-lock.json
  groundzero/package.json
  groundzero/src/App.jsx
  groundzero/src/assets/index.jsx
  groundzero/src/assets/right-arrow.png
  groundzero/src/assets/sample-icon.png
  groundzero/src/components/DisplayButton.jsx
  groundzero/src/components/NavigationBar.jsx
  groundzero/src/components/ProblemStatementCountdown.jsx
  groundzero/src/components/ProblemStatements.jsx
  groundzero/src/components/index.js
  groundzero/src/components/problem-statement-components/StatementCard.jsx
  groundzero/src/components/problem-statement-components/StatementDetails.jsx
  groundzero/src/constants/index.js
  groundzero/src/index.css
  groundzero/src/main.jsx
  groundzero/src/style.js
Labels: bug
